
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLAS = 22;
  public static final int AS = 26;
  public static final int IDENTIFIER = 6;
  public static final int FROM = 91;
  public static final int DECINT = 93;
  public static final int INCLUDE_ONCE = 57;
  public static final int ENDDECLARE = 41;
  public static final int IMPLEMENTS = 55;
  public static final int CONST = 33;
  public static final int CALLABLE = 28;
  public static final int NAMESPACE = 64;
  public static final int EVAL = 47;
  public static final int ISSET = 61;
  public static final int REQUIRE = 77;
  public static final int CATCH = 30;
  public static final int ENDSWITCH = 45;
  public static final int THROW = 82;
  public static final int REQUIRE_ONCE = 78;
  public static final int PREGUNTA_A = 4;
  public static final int DECLARE = 35;
  public static final int OP_RELACIONAL = 12;
  public static final int INSTEADOF = 59;
  public static final int YIELD = 90;
  public static final int PROTECTED = 75;
  public static final int CORCHETE_C = 21;
  public static final int MATCH = 63;
  public static final int ELSEIF = 40;
  public static final int ARRAY = 25;
  public static final int CORCHETE_A = 20;
  public static final int VAR = 87;
  public static final int FINAL = 50;
  public static final int GOTO = 54;
  public static final int HALT_COMPILER = 2;
  public static final int LLAVE_C = 19;
  public static final int ENDWHILE = 46;
  public static final int LLAVE_A = 18;
  public static final int EMPTY = 39;
  public static final int CLASS = 31;
  public static final int INCLUDE = 56;
  public static final int COMA = 94;
  public static final int ABSTRACT = 23;
  public static final int ENDFOR = 42;
  public static final int PHP_I = 92;
  public static final int USE = 86;
  public static final int WHILE = 69;
  public static final int EXTENDS = 49;
  public static final int EACH = 71;
  public static final int INTERFACE = 60;
  public static final int DOSPUNTOS = 96;
  public static final int SWITCH = 81;
  public static final int OP_BOOL = 15;
  public static final int VARIABLE = 88;
  public static final int DO = 68;
  public static final int FOR = 70;
  public static final int RETURN = 79;
  public static final int PUBLIC = 76;
  public static final int TRY = 84;
  public static final int ELSE = 67;
  public static final int BREAK = 27;
  public static final int OP_INCREODEC = 14;
  public static final int ECHO = 38;
  public static final int PARENTESIS_C = 17;
  public static final int PARENTESIS_A = 16;
  public static final int EOF = 0;
  public static final int DIE = 37;
  public static final int DEFAULT = 36;
  public static final int ENDFOREACH = 43;
  public static final int SUMA = 8;
  public static final int PRINT = 73;
  public static final int FUNCTION = 52;
  public static final int ENDIF = 44;
  public static final int OP_LOGICO = 11;
  public static final int APOSTROFE = 95;
  public static final int OR = 72;
  public static final int error = 1;
  public static final int EXIT = 48;
  public static final int RESTA = 9;
  public static final int UNSET = 85;
  public static final int FINALLY = 51;
  public static final int CONTINUE = 34;
  public static final int LIST = 62;
  public static final int IF = 66;
  public static final int INSTANCEOF = 58;
  public static final int MENORQ = 3;
  public static final int OP_ATRIBUCION = 13;
  public static final int MAYORQ = 7;
  public static final int CLONE = 32;
  public static final int GLOBAL = 53;
  public static final int CASE = 29;
  public static final int MULTIPLICA = 10;
  public static final int NEW = 65;
  public static final int AND = 24;
  public static final int PRIVATE = 74;
  public static final int STATIC = 80;
  public static final int P_COMA = 5;
  public static final int XOR = 89;
  public static final int TRAIT = 83;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HALT_COMPILER",
  "MENORQ",
  "PREGUNTA_A",
  "P_COMA",
  "IDENTIFIER",
  "MAYORQ",
  "SUMA",
  "RESTA",
  "MULTIPLICA",
  "OP_LOGICO",
  "OP_RELACIONAL",
  "OP_ATRIBUCION",
  "OP_INCREODEC",
  "OP_BOOL",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "COMILLAS",
  "ABSTRACT",
  "AND",
  "ARRAY",
  "AS",
  "BREAK",
  "CALLABLE",
  "CASE",
  "CATCH",
  "CLASS",
  "CLONE",
  "CONST",
  "CONTINUE",
  "DECLARE",
  "DEFAULT",
  "DIE",
  "ECHO",
  "EMPTY",
  "ELSEIF",
  "ENDDECLARE",
  "ENDFOR",
  "ENDFOREACH",
  "ENDIF",
  "ENDSWITCH",
  "ENDWHILE",
  "EVAL",
  "EXIT",
  "EXTENDS",
  "FINAL",
  "FINALLY",
  "FUNCTION",
  "GLOBAL",
  "GOTO",
  "IMPLEMENTS",
  "INCLUDE",
  "INCLUDE_ONCE",
  "INSTANCEOF",
  "INSTEADOF",
  "INTERFACE",
  "ISSET",
  "LIST",
  "MATCH",
  "NAMESPACE",
  "NEW",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "EACH",
  "OR",
  "PRINT",
  "PRIVATE",
  "PROTECTED",
  "PUBLIC",
  "REQUIRE",
  "REQUIRE_ONCE",
  "RETURN",
  "STATIC",
  "SWITCH",
  "THROW",
  "TRAIT",
  "TRY",
  "UNSET",
  "USE",
  "VAR",
  "VARIABLE",
  "XOR",
  "YIELD",
  "FROM",
  "PHP_I",
  "DECINT",
  "COMA",
  "APOSTROFE",
  "DOSPUNTOS"
  };
}

